### ISSUE TITLE
older netCDF4 version are not supported

### ISSUE THREAD

**Issue by cpaulik** [TUW-GEO/pynetCF#3]
e.g. https://github.com/TUW-GEO/pynetCF/blob/master/pynetcf/time_series.py#L992 does not work when using netCDF==1.0.8

So we either make this clear in the requirements or we fix the problem which is just the missing [:] after the variable.

**Comment by sebhahn** [comment]
adding [:] is probably the better solution

**Comment by sebhahn** [comment]
I'm closing this issue, because the netCDF is already at version 1.5
