### ISSUE TITLE
Pynetcf 2.2 requires netcdf4>=1.4.0

### ISSUE THREAD

**Issue by Lmoesinger** [TUW-GEO/pynetcf#51]
Since this commit ( https://github.com/TUW-GEO/pynetcf/commit/a7ee3a90ddab5da5ab4214e4012b4f944b5d18b8 ) `netcd4.num2date()` is called with the kwarg `only_use_cftime_datetimes`. This is kwarg is only available since netcdf4>=1.4.0, if an older version is used a typeerror is thrown:

`TypeError: num2date() got an unexpected keyword argument 'only_use_cftime_datetimes'`

So I guess the proper course is either to update the requirements to match, or revert this commit.

**Comment by sebhahn** [comment]
the package has the requirement to use netcdf>=1.4.2

https://github.com/TUW-GEO/pynetcf/blob/master/setup.cfg#L33

if you work with an older version of netcdf please install a older version of pynetcf

**Comment by Lmoesinger** [comment]
I see, i apparently managed to circumvent the requirements by installing netcdf4 with with conda, and pynetcf with pip. My bad, thanks for your time!
