### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by s-scherrer** [TUW-GEO/pynetcf#56]
I saw that the last release is already quite some time ago, is it possible to create a new release for this? I'm currently running into issues in another package that uses pynetcf, because the old version still uses `np.int`, which has now been removed from the most up to date numpy version.

**Comment by wpreimes** [comment]
@sebhahn said some time ago that the changes in the master branch should **not** be released yet. Is this still the case?

**Comment by sebhahn** [comment]
I will create a new release without the latest changes (ie. before refactoring the code), but including the 'np.int' fix

**Comment by sebhahn** [comment]
@s-scherrer @wpreimes I created a new release (v0.2.3)
